# -*- coding: utf-8 -*-
"""Programa Ecu Dif

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okC6rW5QY8sFObq0qfSNHOnR2bANFUO-
"""

from pyngrok import ngrok, conf
conf.get_default().auth_token = "2xWTWPwYDlZ68r2MjxeYHe8uLcM_2yc7pkUVLXMUEEhii1a78"

app_code = '''
# Se implementan y designan las funciones para Streamlit
import streamlit as st
import json
import os
import math
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

def cargar_usuarios():
    if os.path.exists("usuarios.json"):
        with open("usuarios.json", "r") as f:
            return json.load(f)
    return {}

def guardar_usuarios(data):
    with open("usuarios.json", "w") as f:
        json.dump(data, f, indent=4)

# ------------------ Inicialización de estados ------------------

if "usuario_validado" not in st.session_state:
    st.session_state.usuario_validado = False
if "resultado_generado" not in st.session_state:
    st.session_state.resultado_generado = False
if "resultado_guardado" not in st.session_state:
    st.session_state.resultado_guardado = False
if "resultado" not in st.session_state:
    st.session_state.resultado = ""
if "mostrar_encuesta" not in st.session_state:
    st.session_state.mostrar_encuesta = False
if "encuesta_iniciada" not in st.session_state:
    st.session_state.encuesta_iniciada = False

usuarios = cargar_usuarios()

# ------------------ Formulario de ingreso ------------------

if not st.session_state.usuario_validado:
    st.title("Ingreso de Usuario 🩺")
    nombre = st.text_input("Ingrese su nombre")
    id_usuario = st.text_input("Ingrese su identificación")

    if nombre and id_usuario:
        st.session_state.nombre = nombre
        st.session_state.id_usuario = id_usuario
        st.session_state.usuario_validado = True

# ------------------ Lógica principal ------------------

if st.session_state.usuario_validado:
    nombre = st.session_state.nombre
    id_usuario = st.session_state.id_usuario
    seccion_inicio1 = st.empty()
    seccion_inicio2 = st.empty()

    if (
        id_usuario in usuarios
        and usuarios[id_usuario].get("resultado")
        and not st.session_state.mostrar_encuesta
        and not st.session_state.encuesta_iniciada
    ):
      with seccion_inicio1.container():
        fecha_guardada = usuarios[id_usuario].get("fecha_resultado")
        if fecha_guardada:
            fecha_resultado = datetime.strptime(fecha_guardada, "%Y-%m-%d")
            fecha_actual = datetime.now()
            dias_transcurridos = (fecha_actual - fecha_resultado).days
            meses_transcurridos = dias_transcurridos / 30.44  # promedio de días por mes

        # Extraer tiempo original del mensaje guardado (o guardar como número aparte)
        tiempo_original = 39  # o extraído desde usuarios[id_usuario]["tiempo_estimado"]
        tiempo_actualizado = max(0, tiempo_original - meses_transcurridos)
        st.success(f"Bienvenido nuevamente, {usuarios[id_usuario]['nombre']} 👋")
        st.subheader("📋 Resultado anterior:")
        st.write(usuarios[id_usuario]["resultado"])
        if "grafica" in usuarios[id_usuario]:
          st.image(usuarios[id_usuario]["grafica"], caption="📊 Evolución estimada del tumor", use_container_width=True)
        if "imagen_ilustrativa" in usuarios[id_usuario]:
          st.image(usuarios[id_usuario]["imagen_ilustrativa"], caption="🖼️ Ilustración del resultado")

        if st.button("🔁 Repetir formulario"):
            st.session_state.encuesta_iniciada = True
            st.session_state.mostrar_encuesta = True
            st.session_state.resultado_generado = False
            st.session_state.resultado_guardado = False
            seccion_inicio1.empty()
    # Mostrar mensaje solo si es nuevo y aún no ha generado resultado
    elif id_usuario not in usuarios and not st.session_state.resultado_generado and not st.session_state.encuesta_iniciada:
      with seccion_inicio2.container():
        st.info("🆕 Usuario nuevo detectado. Bienvenido. Pulse para iniciar el formulario.")
        if st.button("Iniciar"):
            st.session_state.encuesta_iniciada = True
            st.session_state.mostrar_encuesta = True
            seccion_inicio2.empty()

if st.session_state.encuesta_iniciada:
    # Configuración inicial
    st.set_page_config(page_title="Diagnóstico Asistido", layout="centered")

    # Se crea una variable de sesión para los pasos del programa
    if 'paso' not in st.session_state:
        st.session_state.paso = 1

    # Se crea una función para avanzar de paso
    def siguiente_paso():
        st.session_state.paso += 1

    # Inicializar estados de sesión
    if "resultado_generado" not in st.session_state:
        st.session_state.resultado_generado = False
    if "resultado_guardado" not in st.session_state:
        st.session_state.resultado_guardado = False

    # Paso 1: Pregunta inicial
    if st.session_state.paso == 1:
        paso1_container = st.empty()          # Contiene el formulario y el título junto con una función para eliminar a la vista lo que se muestra en este paso al avanzar al siguiente
        # Se presentan las preguntas con un formato de formulario
        with paso1_container.form("inicio_form"):
            st.title("Apoyo General - Cáncer de Cuello Uterino")                                                          # Inserta un titulo para el formulario
            inicio = st.radio("¿Tiene cáncer de cuello uterino diagnosticado?", ["Sí", "No"], key="diagnosticado")        # Muestra la pregunta dentro del parentesis
            submitted = st.form_submit_button("Siguiente")  # Botón dentro del formulario                                 # Inserta un botón dentro del formulario para avanzar al siguiente paso

        # Se valida que el usuario haya presionado el botón dentro del formulario
        if submitted:
            st.session_state.inicio = inicio  # Guardamos la respuesta
            st.session_state.paso += 1  # Avanzamos al siguiente paso
            st.rerun()                  # Se genera una actualización rapida en la página para guardar los datos y pasar inmediatamente al siguiente paso
            paso1_container.empty()     # Borra u oculta lo que se muestra en el paso presente

    # Paso 2: Preguntas clínicas
    if st.session_state.paso == 2:
        with st.form("preguntas_clinicas"):
            if st.session_state.inicio == "Sí":
                st.title("Evaluación General de Estado - Cáncer de Cuello Uterino")
            else:
                st.title("Diagnóstico General Asistido - Cáncer de Cuello Uterino")

            sv = st.radio("¿Ha presentado sangrado vaginal fuera del periodo menstrual?", ["Sí", "No"], key="svm")
            srx = st.radio("¿Ha tenido sangrado después de tener relaciones sexuales?", ["Sí", "No"], key="srsx")
            fo = st.radio("¿Ha notado flujo vaginal con mal olor?", ["Sí", "No"], key="fol")
            fc = st.radio("¿Ha notado un flujo vaginal diferente al habitual? (color o textura diferente)", ["Sí", "No"], key="fd")
            df = st.radio("¿Siente dolor pélvico o en la parte baja del abdomen?", ["Sí", "No"], key="dfp")
            drx = st.radio("¿Ha sentido dolor durante las relaciones sexuales?", ["Sí", "No"], key="drsx")

            submitted = st.form_submit_button("Siguiente")
            if submitted:
                st.session_state.sm = sv
                st.session_state.srs = srx
                st.session_state.fvo = fo
                st.session_state.fvc = fc
                st.session_state.dp = df
                st.session_state.drs = drx
                st.session_state.paso += 1
                st.rerun()


    # Paso 3: Detalles
    elif st.session_state.paso == 3:
        resin = [
            st.session_state.sm == "Sí",
            st.session_state.srs == "Sí",
            st.session_state.fvo == "Sí",
            st.session_state.fvc == "Sí",
            st.session_state.dp == "Sí",
            st.session_state.drs == "Sí"
        ]

        respu = sum(resin)  # Hace una sumatoria de las respuestas que son "Sí"
        st.session_state.respu = respu

        sre1 = st.session_state.respu * 0.05                # Se multiplica el numero de respuestas positivas por un valor dado a la gravedad de la pregunta
        st.session_state.sre1 = sre1
        smax = 2.65
        rmin = 0.17
        rmax = 0.44

        def calcular_tiempo_vida(P0, K, r):
            argumento = (K - P0) / P0
            if argumento <= 0:
                return None  # Evita logaritmo de número no positivo
            t = (1 / r) * math.log(argumento)
            return t

        # Parámetros clínicos
        P0 = 1.5     # Tamaño inicial del tumor en cm³
        K = 1344     # Tamaño máximo del tumor en cm³
        r = rmin + (rmax - rmin) * (sre1 / smax)     # Tasa de crecimiento ajustada según síntomas

        # Cálculo
        t_estimada = calcular_tiempo_vida(P0, K, r)
        meses = math.ceil(t_estimada)  # Redondear hacia arriba

        def graficar_logistica(P0, K, r):
            C = (K - P0) / P0
            t = np.linspace(0, 100, 200)  # tiempo en semanas
            P = K / (1 + C * np.exp(-r * t))

            fig, ax = plt.subplots()
            ax.plot(t, P, label="Crecimiento tumoral", color="crimson")
            ax.set_xlabel("Tiempo (semanas)")
            ax.set_ylabel("Tamaño del tumor (cm³)")
            ax.set_title("Modelo logístico de crecimiento tumoral")
            ax.grid(True)
            ax.legend()

            # Generar nombre único del archivo
            nombre_archivo = f"grafica_{st.session_state.id_usuario}.png"
            fig.savefig(nombre_archivo)
            plt.close(fig)

            return nombre_archivo


        nuevas_preguntas = False                    # Esto es para determinar si se deben mostrar preguntas nuevas o mostrar un resultado a este punto
        paso3_container = st.empty()
        with paso3_container.form("detalles_form"):
          if st.session_state.inicio == "Sí":
              st.title("Evaluación General de Estado - Cáncer de Cuello Uterino")
          else:
              st.title("Diagnóstico General Asistido - Cáncer de Cuello Uterino")

          if (st.session_state.sm == "Sí" or st.session_state.srs == "Sí") and st.session_state.respu >= 2:
            sgr = st.radio("Los episodios de sangrado vaginal extraordinarios ¿Son leves?", ["Sí", "No"], key="sangrado")
            st.session_state.sgr = sgr
            nuevas_preguntas = True  # Marcar que se hizo una pregunta
          else:
            st.session_state.sgr = "No"

          if (st.session_state.srs == "Sí" or st.session_state.drs == "Sí") and st.session_state.respu >= 2:
            rsx = st.radio("¿Las molestias que presenta son solo al tener relaciones sexuales?", ["Sí", "No"], key="relaciones")
            st.session_state.rsx = rsx
            nuevas_preguntas = True
          else:
            st.session_state.rsx = "No"

          if st.session_state.fvo == "Sí" and st.session_state.respu >= 2:
            st.session_state.foo = st.radio("¿El flujo con mal olor aparece con frecuencia?", ["Sí", "No"], key="folor")
            nuevas_preguntas = True
          else:
            st.session_state.foo = "No"

          if st.session_state.dp == "Sí" and st.session_state.respu >= 2:
            dpv = st.radio("¿El dolor pélvico es leve y ocasional?", ["Sí", "No"], key="pelvico")
            st.session_state.dpv = dpv
            nuevas_preguntas = True
          else:
            st.session_state.dpv = "No"

          submitted = st.form_submit_button("Siguiente")  # Botón dentro del formulario
          if submitted:
            st.session_state.paso += 1
            st.rerun()
            paso3_container.empty()

        # Si NO se abrieron nuevas preguntas, mostrar los avisos
        if not nuevas_preguntas:
          paso3_container.empty()
          if st.session_state.inicio == "Sí" and st.session_state.fvc == "Sí" and st.session_state.respu == 1:
            st.title("Resultado de la Evaluación de Estado")
            mensaje = f"Puede tener un Estadio 0 o carcinoma in situ, es una etapa precancerosa en la que ya se han detectado células cancerosas. Su condición no debe ser crítica ni avanzada y si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; aunque en Estadio 0 la evolución puede ser más lenta que lo estimado (Es un resultado teórico, no reemplaza un diagnóstico médico real). Se recomienda seguir un tratamiento adecuado para mantenerlo en dicho estado o directamente erradicarlo."
            st.success(mensaje)
            imagen_ilustrativa = "imagenes/estadio_0.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = graficar_logistica(P0, K, r)
            st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
          elif st.session_state.inicio == "Sí" and st.session_state.respu <= 1:
            st.title("Resultado de la Evaluación de Estado")
            mensaje = f"Puede tener un Estadio 0 o carcinoma in situ, es una etapa precancerosa en la que ya se han detectado células cancerosas. Su condición no debe ser crítica ni avanzada y si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; aunque en Estadio 0 la evolución puede ser más lenta que lo estimado (Es un resultado teórico, no reemplaza un diagnóstico médico real). Se recomienda seguir un tratamiento adecuado para mantenerlo en dicho estado o directamente erradicarlo."
            st.success(mensaje)
            imagen_ilustrativa = "imagenes/estadio_0.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = graficar_logistica(P0, K, r)
            st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
          elif st.session_state.inicio == "No" and st.session_state.fvc == "Sí" and st.session_state.respu == 1:
            st.title("Diagnóstico General Obtenido")
            mensaje = """No se puede considerar que tenga un condición al punto de cáncer, pero no se descarta una infección, irritación, maltrato y/o lesión.
            Se recomienda una cita con un especialista para una revisión y obtener un diagnóstico preciso y más seguro."""
            st.success(mensaje)
            imagen_ilustrativa = None
            nombre_imagen = None
          elif st.session_state.inicio == "No" and st.session_state.respu <= 1:
            st.title("Diagnóstico General Obtenido")
            mensaje = """No se puede considerar que tenga un condición al punto de cáncer o cercana.
            Se recomienda una cita con un especialista para una revisión y  estudio, así descartar dudas y tener un diagnóstico más seguro."""
            st.success(mensaje)
            imagen_ilustrativa = None
            nombre_imagen = None

          st.session_state.resultado = mensaje
          st.session_state.resultado_generado = True
          st.session_state.resultado_guardado = False  # Por si el usuario quiere repetir

          # Mostrar botón para guardar
          # 🟠 Advertencia si intenta salir sin guardar
          if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
              st.warning("Guarda tu resultado y podrás verlo en una siguiente sesión.")

          if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
              if st.button("Guardar resultado"):
                  datos_resultado = {
                      "nombre": nombre,
                      "resultado": mensaje,
                      "fecha_resultado": datetime.now().strftime("%Y-%m-%d"),
                  }

                  # Solo agregar si existen
                  if nombre_imagen:
                      datos_resultado["grafica"] = nombre_imagen

                  if imagen_ilustrativa:
                      datos_resultado["imagen_ilustrativa"] = imagen_ilustrativa

                  usuarios[id_usuario] = datos_resultado
                  guardar_usuarios(usuarios)
                  st.session_state.resultado_guardado = True
                  st.success("✅ Resultado guardado.")

    # Paso 4: Avances
    if st.session_state.paso == 4:
        resin = [
            st.session_state.sgr == "Sí",
            st.session_state.fvo == "Sí",
            st.session_state.fvc == "Sí",
            st.session_state.dpv == "Sí",
            st.session_state.rsx == "Sí"
        ]

        respd = sum(resin)  # Hace una sumatoria de las respuestas que son "Sí"
        st.session_state.respd = respd

        suma = [
          st.session_state.sgr == "Sí",
          st.session_state.rsx == "Sí",
          st.session_state.dpv == "Sí"
        ]
        sre = sum(suma) * 0.05
        sre2 = sre + st.session_state.sre1
        st.session_state.sre2 = sre2
        smax = 2.65
        rmin = 0.17
        rmax = 0.44

        def calcular_tiempo_vida(P0, K, r):
            argumento = (K - P0) / P0
            if argumento <= 0:
                return None  # Evita logaritmo de número no positivo
            t = (1 / r) * math.log(argumento)
            return t

        # Parámetros clínicos
        P0 = 1.5     # Tamaño inicial del tumor en cm³
        K = 1344     # Tamaño máximo del tumor en cm³
        r = rmin + (rmax - rmin) * (sre2 / smax)     # Tasa de crecimiento ajustada según síntomas

        # Cálculo
        t_estimada = calcular_tiempo_vida(P0, K, r)
        meses = math.ceil(t_estimada)  # Redondear hacia arriba

        def graficar_logistica(P0, K, r):
            C = (K - P0) / P0
            t = np.linspace(0, 100, 200)  # tiempo en semanas
            P = K / (1 + C * np.exp(-r * t))

            fig, ax = plt.subplots()
            ax.plot(t, P, label="Crecimiento tumoral", color="crimson")
            ax.set_xlabel("Tiempo (semanas)")
            ax.set_ylabel("Tamaño del tumor (cm³)")
            ax.set_title("Modelo logístico de crecimiento tumoral")
            ax.grid(True)
            ax.legend()

            # Generar nombre único del archivo
            nombre_archivo = f"grafica_{st.session_state.id_usuario}.png"
            fig.savefig(nombre_archivo)
            plt.close(fig)

            return nombre_archivo

        # Si hay respuestas "Sí", mostrar preguntas adicionales primero
        nuevas_preguntas = False
        paso4_container = st.empty()
        with paso4_container.form("avances_form"):
            if st.session_state.inicio == "Sí":
                st.title("Evaluación General de Estado - Cáncer de Cuello Uterino")
            else:
                st.title("Diagnóstico General Asistido - Cáncer de Cuello Uterino")

            if (st.session_state.sm == "Sí" or st.session_state.srs == "Sí") and st.session_state.sgr == "No":
                st.session_state.sab = st.radio("Los sangrados vaginales ¿Son persistentes y/o abundantes?", ["Sí", "No"], key="sabundante")
                nuevas_preguntas = True
            else:
                st.session_state.sab = "No"

            if st.session_state.dp == "Sí" and st.session_state.dpv == "No":
                st.session_state.dpe = st.radio("¿Siente dolor frecuente o constante en la pelvis y/o la parte baja de la espalda?", ["Sí", "No"], key="pelve")
                st.session_state.dor = st.radio("¿Ha tenido dolor al orinar?", ["Sí", "No"], key="orina")
                st.session_state.dde = st.radio("¿Ha tenido dolor al defecar?", ["Sí", "No"], key="defeccion")
                nuevas_preguntas = True
            else:
                st.session_state.dpe = "No"
                st.session_state.dor = "No"
                st.session_state.dde = "No"

            if st.session_state.respu >= 3 and st.session_state.foo == "Sí":
                st.session_state.hpp = st.radio("¿Ha notado hinchazón en las piernas o pies sin razón aparente?", ["Sí", "No"], key="hinchazon")
                nuevas_preguntas = True
            else:
                st.session_state.hpp = "No"

            submitted = st.form_submit_button("Siguiente")  # Botón dentro del formulario
        if submitted:
          st.session_state.paso += 1  # Solo avanza después de presionar el botón dentro del formulario
          st.rerun()
          paso4_container.empty()

        # Si NO se abrieron nuevas preguntas, mostrar los avisos
        if not nuevas_preguntas:
          paso4_container.empty()
          if st.session_state.inicio == "Sí" and st.session_state.respd >= 0:
            st.title("Resultado de la Evaluación de Estado")
            mensaje = f"El cáncer puede encontrarse en Estadio I, en esta etapa el cáncer está detectado y localizado únicamente en el cuello uterino, no suele estar extendido a otras partes del útero. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se recomienda seguir con regularidad los tratamientos indicados por los especialistas para controlar el tumor y potencialmente suprimirlo."
            st.info(mensaje)
            imagen_ilustrativa = "imagenes/estadio_1.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = graficar_logistica(P0, K, r)
            st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
          elif st.session_state.inicio == "No" and st.session_state.respd >= 0:
            st.title("Diagnóstico General Obtenido")
            mensaje = f"Los síntomas presentados indican la posibilidad de presentar cáncer de cuello uterino, puede estar entre Estadio 0 y I, en estas etapas las células cancerosas empiezan a desarrollarse o pueden llegar a encontrarse solo en el cuello uterino, sin llegar a extenderse a otras zonas del órgano. Se indica visitar lo más pronto posible un especialista para tener seguridad de su estado y empezar con los tratamientos pertinentes para mejorar su estado, de ser necesario."
            st.info(mensaje)
            imagen_ilustrativa = "imagenes/estadio_01.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor (A: Estadio 0; B: Estadio I)", use_container_width=True)
            nombre_imagen = None

          st.session_state.resultado = mensaje
          st.session_state.resultado_generado = True
          st.session_state.resultado_guardado = False  # Por si el usuario quiere repetir

          # Mostrar botón para guardar
          # 🟠 Advertencia si intenta salir sin guardar
          if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
              st.warning("Guarda tu resultado y podrás verlo en una siguiente sesión.")

          if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
              if st.button("Guardar resultado"):
                  datos_resultado = {
                      "nombre": nombre,
                      "resultado": mensaje,
                      "fecha_resultado": datetime.now().strftime("%Y-%m-%d"),
                  }

                  # Solo agregar si existen
                  if nombre_imagen:
                      datos_resultado["grafica"] = nombre_imagen

                  if imagen_ilustrativa:
                      datos_resultado["imagen_ilustrativa"] = imagen_ilustrativa

                  usuarios[id_usuario] = datos_resultado
                  guardar_usuarios(usuarios)
                  st.session_state.resultado_guardado = True
                  st.success("✅ Resultado guardado.")

    # Paso 5: Criticismo
    elif st.session_state.paso == 5:
        respin = [
            (st.session_state.sab == "Sí") * 2,
            (st.session_state.foo == "Sí") * 2,
            (st.session_state.fvc == "Sí") * 1,
            (st.session_state.dpe == "Sí") * 2,
            (st.session_state.dor == "Sí") * 1,
            (st.session_state.dde == "Sí") * 1,
            (st.session_state.hpp == "Sí") * 2
        ]

        respt = sum(respin)  # Cuenta cuántas respuestas son "Sí"
        st.session_state.respt = respt

        suma = [
          st.session_state.sab == "Sí",
          st.session_state.foo == "Sí",
          st.session_state.dpe == "Sí",
          st.session_state.dor == "Sí",
          st.session_state.dde == "Sí",
          st.session_state.hpp == "Sí"
        ]
        sre = sum(suma) * 0.1
        sre3 = sre + st.session_state.sre2
        st.session_state.sre3 = sre3
        smax = 2.65
        rmin = 0.17
        rmax = 0.44

        def calcular_tiempo_vida(P0, K, r):
            argumento = (K - P0) / P0
            if argumento <= 0:
                return None  # Evita logaritmo de número no positivo
            t = (1 / r) * math.log(argumento)
            return t

        # Parámetros clínicos
        P0 = 1.5     # Tamaño inicial del tumor en cm³
        K = 1344     # Tamaño máximo del tumor en cm³
        r = rmin + (rmax - rmin) * (sre3 / smax)     # Tasa de crecimiento ajustada según síntomas

        # Cálculo
        t_estimada = calcular_tiempo_vida(P0, K, r)
        meses = math.ceil(t_estimada)  # Redondear hacia arriba

        def graficar_logistica(P0, K, r):
            C = (K - P0) / P0
            t = np.linspace(0, 100, 200)  # tiempo en semanas
            P = K / (1 + C * np.exp(-r * t))

            fig, ax = plt.subplots()
            ax.plot(t, P, label="Crecimiento tumoral", color="crimson")
            ax.set_xlabel("Tiempo (semanas)")
            ax.set_ylabel("Tamaño del tumor (cm³)")
            ax.set_title("Modelo logístico de crecimiento tumoral")
            ax.grid(True)
            ax.legend()

            # Generar nombre único del archivo
            nombre_archivo = f"grafica_{st.session_state.id_usuario}.png"
            fig.savefig(nombre_archivo)
            plt.close(fig)

            return nombre_archivo

        # Si hay respuestas "Sí", mostrar preguntas adicionales primero
        nuevas_preguntas = False
        paso5_container = st.empty()
        with paso5_container.form("criticismo_form"):
          if st.session_state.inicio == "Sí":
              st.title("Evaluación General de Estado - Cáncer de Cuello Uterino")
          else:
              st.title("Diagnóstico General Asistido - Cáncer de Cuello Uterino")

          if st.session_state.dor == "Sí" or st.session_state.dde == "Sí" or st.session_state.sab == "Sí":
            st.session_state.sro = st.radio("¿Ha tenido sangrado por el recto o sangre en la orina?", ["Sí", "No"], key="sanro")
            nuevas_preguntas = True
          else:
            st.session_state.sro = "No"

          if st.session_state.dor == "Sí":
            st.session_state.cno = st.radio("¿Ha notado dificultad para orinar o controlar la orina?", ["Sí", "No"], key="controlo")
            nuevas_preguntas = True
          else:
            st.session_state.cno = "No"

          if st.session_state.dde == "Sí":
            st.session_state.cnh = st.radio("¿Tiene dificultad para defecar o controlar las heces?", ["Sí", "No"], key="controlh")
            nuevas_preguntas = True
          else:
            st.session_state.cnh = "No"

          if st.session_state.dpe == "Sí":
            st.session_state.dcf = st.radio("¿Tiene dolor crónico intenso en el abdomen, pelvis o espalda baja que afecta sus actividades diarias?", ["Sí", "No"], key="cronico")
            nuevas_preguntas = True
          else :
            st.session_state.dcf = "No"

          if st.session_state.respt >= 4 and st.session_state.hpp == "Sí":
            st.session_state.pe = st.radio("¿Ha perdido peso de manera involuntaria y significativa en los últimos meses?", ["Sí", "No"], key="peso")
            st.session_state.ca = st.radio("¿Se siente extraordinariamente cansada sin razón aparente?", ["Sí", "No"], key="cansancio")
            st.session_state.tos = st.radio("¿Tiene tos persistente o dificultad para respirar sin causa respiratoria clara?", ["Sí", "No"], key="respiracion")
            st.session_state.dos = st.radio("¿Ha tenido dolor óseo o fracturas recientes sin traumatismos fuertes?", ["Sí", "No"], key="huesos")
            nuevas_preguntas = True
          else:
            st.session_state.pe = "No"
            st.session_state.ca = "No"
            st.session_state.tos = "No"
            st.session_state.dos = "No"

          submitted = st.form_submit_button("Siguiente")  # Botón dentro del formulario
        if submitted:
          st.session_state.paso += 1
          st.rerun()

        # Si NO se abrieron nuevas preguntas, mostrar los avisos
        if not nuevas_preguntas:
          paso5_container.empty()
          if st.session_state.inicio == "Sí" and st.session_state.respt >= 0:
            st.title("Resultado de la Evaluación de Estado")
            mensaje = f"Muestra síntomas que indican estar en Estadio II, en esta etapa el tumor ha invadido el útero y puede llegar a afectar la zona superior de la vagina, no afecta la zona inferior de esta ni la pared pélvica. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica continuar con los tratamientos requeridos con regularidad y seguir las indicaciones dadas por los especialistas para evitar la progresión del cáncer y no verse mucho más afectada."
            st.warning(mensaje)
            imagen_ilustrativa = "imagenes/estadio_2.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = graficar_logistica(P0, K, r)
            st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
          elif st.session_state.inicio == "Sí" and st.session_state.respt >= 5:
            st.title("Resultado de la Evaluación de Estado")
            mensaje = f"Muestra síntomas que indican estar en Estadio II o avanzando a Estadio III, en esta etapa el tumor ha invadido el útero y puede llegar a afectar la zona superior de la vagina, es posible que se esté extendiendo hacia la zona inferior de esta y parcialmente a la pared pélvica. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica continuar con los tratamientos requeridos con regularidad y seguir las indicaciones dadas por los especialistas para evitar la progresión del cáncer al siguiente estadio en su totalidad y verse mucho más afectada."
            st.warning(mensaje)
            imagen_ilustrativa = "imagenes/estadio_23.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor (C: Estadio II; D: Estadio III)", use_container_width=True)
            nombre_imagen = graficar_logistica(P0, K, r)
            st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
          elif st.session_state.inicio == "Sí" and st.session_state.respt >= 8:
            st.title("Resultado de la Evaluación de Estado")
            mensaje = f"Muestra síntomas que indican estar en etapa temprana/media del Estadio III, en esta etapa el tumor ha invadido el útero, gran parte de la vagina, ganglios linfáticos en la zona y hasta la pared pélvica; puede incluso llegar parcialmente hasta el riñón y afectar su funcionamiento. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica continuar con los tratamientos requeridos con rigurosidad y seguir las indicaciones dadas por los especialistas para evitar la progresión del cáncer hasta una etapa terminal y más crítica."
            st.warning(mensaje)
            imagen_ilustrativa = "imagenes/estadio_3.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = graficar_logistica(P0, K, r)
            st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
          elif st.session_state.inicio == "No" and st.session_state.respt >= 0:
            st.title("Diagnóstico General Obtenido")
            mensaje = f"Hay síntomas que generan una alta posibilidad de presentar cáncer en un estado medio, puede estar en Estadio II o cercano a este, durante esta etapa el útero en sí se ve afectado y, en cierta medida, la zona superior de la vagina, no llega hasta la parte inferior ni a la pared pélvica. Se recomienda visitar un especialista tan pronto como pueda para obtener un diagnóstico oficial y, de ser necesario, empezar inmediatamente con los tratamientos requeridos para controlar su situación y prevenir avances en esta."
            st.warning(mensaje)
            imagen_ilustrativa = "imagenes/estadio_2.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = None
          elif st.session_state.inicio == "No" and st.session_state.respt >= 5:
            st.title("Diagnóstico General Obtenido")
            mensaje = f"Hay síntomas que generan una alta posibilidad de presentar cáncer en un estado medio, puede estar en Estadio II, durante esta etapa el útero en sí se ve afectado y, en cierta medida, la zona superior de la vagina, no llega hasta la parte inferior ni a la pared pélvica. Se recomienda visitar un especialista tan pronto como pueda para obtener un diagnóstico oficial y, de ser necesario, empezar inmediatamente con los tratamientos requeridos para controlar su situación y prevenir avances en esta."
            st.warning(mensaje)
            imagen_ilustrativa = "imagenes/estadio_2.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
            nombre_imagen = None
          elif st.session_state.inicio == "No" and st.session_state.respt >= 8:
            st.title("Diagnóstico General Obtenido")
            mensaje = f"Hay síntomas que generan una alta posibilidad de presentar cáncer en un estado medianamente avanzado, puede estar en Estadio II o cercano al Estadio III, durante esta etapa el útero en sí se ve afectado, la zona superior y, en cierta medida, la zona inferior de la vagina, puede llegar hasta la pared pélvica. Se recomienda visitar un especialista tan pronto como pueda para obtener un diagnóstico oficial y, de ser necesario, empezar inmediatamente con los tratamientos requeridos para controlar su situación y prevenir el avance de una etapa a la otra y entrar en una fase más crítica."
            st.warning(mensaje)
            imagen_ilustrativa = "imagenes/estadio_23.png"
            st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor (C: Estadio II; D: Estadio III)", use_container_width=True)
            nombre_imagen = None

          st.session_state.resultado = mensaje
          st.session_state.resultado_generado = True
          st.session_state.resultado_guardado = False  # Por si el usuario quiere repetir

          # Mostrar botón para guardar
          # 🟠 Advertencia si intenta salir sin guardar
          if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
              st.warning("Guarda tu resultado y podrás verlo en una siguiente sesión.")

          if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
              if st.button("Guardar resultado"):
                  datos_resultado = {
                      "nombre": nombre,
                      "resultado": mensaje,
                      "fecha_resultado": datetime.now().strftime("%Y-%m-%d"),
                  }

                  # Solo agregar si existen
                  if nombre_imagen:
                      datos_resultado["grafica"] = nombre_imagen

                  if imagen_ilustrativa:
                      datos_resultado["imagen_ilustrativa"] = imagen_ilustrativa

                  usuarios[id_usuario] = datos_resultado
                  guardar_usuarios(usuarios)
                  st.session_state.resultado_guardado = True
                  st.success("✅ Resultado guardado.")

    # Paso 6: Diagnóstico
    elif st.session_state.paso == 6:
        st.title("Resultado del Análisis")

        respuestas = [
            st.session_state.sro == "Sí",
            st.session_state.cno == "Sí",
            st.session_state.cnh == "Sí",
            st.session_state.dcf == "Sí",
            st.session_state.pe == "Sí",
            st.session_state.ca == "Sí",
            st.session_state.tos == "Sí",
            st.session_state.dos == "Sí"
        ]
        diagfinal = sum(respuestas)

        sre = diagfinal * 0.2
        sre4 = sre + st.session_state.sre3
        st.session_state.sre4 = sre4
        smax = 2.65
        rmin = 0.17
        rmax = 0.44

        def calcular_tiempo_vida(P0, K, r):
            argumento = (K - P0) / P0
            if argumento <= 0:
                return None  # Evita logaritmo de número no positivo
            t = (1 / r) * math.log(argumento)
            return t

        # Parámetros clínicos
        P0 = 1.5     # Tamaño inicial del tumor en cm³
        K = 1344     # Tamaño máximo del tumor en cm³
        r = rmin + (rmax - rmin) * (sre4 / smax)     # Tasa de crecimiento ajustada según síntomas

        # Cálculo
        t_estimada = calcular_tiempo_vida(P0, K, r)
        meses = math.ceil(t_estimada)  # Redondear hacia arriba

        def graficar_logistica(P0, K, r):
            C = (K - P0) / P0
            t = np.linspace(0, 100, 200)  # tiempo en semanas
            P = K / (1 + C * np.exp(-r * t))

            fig, ax = plt.subplots()
            ax.plot(t, P, label="Crecimiento tumoral", color="crimson")
            ax.set_xlabel("Tiempo (semanas)")
            ax.set_ylabel("Tamaño del tumor (cm³)")
            ax.set_title("Modelo logístico de crecimiento tumoral")
            ax.grid(True)
            ax.legend()

            # Generar nombre único del archivo
            nombre_archivo = f"grafica_{st.session_state.id_usuario}.png"
            fig.savefig(nombre_archivo)
            plt.close(fig)

            return nombre_archivo

        if st.session_state.inicio == "Sí" and diagfinal >= 6:
          mensaje = f"Parece estar en Estadio IV, puede ser una etapa temprana o media, durante esta fase el cáncer se ha extendido hacia otros tejidos y órganos aparte del útero y la vagina, puede generar afectaciones en ciertas actividades y necesidades cotidianas; generar sensación de cansancio y dolores constantes en diversas áreas del cuerpo, esta etapa puede ser descrita como 'Metástasis' también. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica seguir los tratamientos necesarios y posiblemente realizar una biopsia para identificar el grado de Estadio IV en que se encuentre para que los especialistas puedan indicarle cómo proseguirá el tratamiento de su cáncer."
          st.error(mensaje)
          imagen_ilustrativa = "imagenes/estadio_4.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
          nombre_imagen = graficar_logistica(P0, K, r)
          st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
        elif st.session_state.inicio == "Sí" and diagfinal >= 4:
          mensaje = f"Parece estar en un Estadio III avanzado o entrando a Estadio IV, durante esta etapa el cáncer está extendiéndose hacia otros tejidos y órganos aparte del útero y la vagina, puede generar afectaciones en ciertas actividades y necesidades cotidianas. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica seguir los tratamientos necesarios y posiblemente realizar una biopsia para identificar el grado de Estadio IV en que se encuentre para que los especialistas puedan indicarle cómo proseguirá el tratamiento de su cáncer."
          st.error(mensaje)
          imagen_ilustrativa = "imagenes/estadio_34.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor (E: Estadio III; F: Estadio IV)", use_container_width=True)
          nombre_imagen = graficar_logistica(P0, K, r)
          st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
        elif st.session_state.inicio == "Sí" and diagfinal >= 2:
          mensaje = f"Muestra síntomas que indican estar en Estadio III medio/avanzado, en esta etapa el tumor ha invadido el útero, gran parte de la vagina, ganglios linfáticos en la zona y hasta la pared pélvica; puede incluso llegar parcialmente hasta el riñón, afectar su funcionamiento y causar molestias al orinar o defecar al afectar la vejiga o el recto hasta cierto punto. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica continuar con los tratamientos requeridos con rigurosidad y seguir las indicaciones dadas por los especialistas para evitar la progresión del cáncer hasta una etapa terminal y más crítica."
          st.warning(mensaje)
          imagen_ilustrativa = "imagenes/estadio_33.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
          nombre_imagen = graficar_logistica(P0, K, r)
          st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
        elif st.session_state.inicio == "Sí" and diagfinal >= 0:
          mensaje = f"Muestra síntomas que indican estar en etapa temprana/media del Estadio III, en esta etapa el tumor ha invadido el útero, gran parte de la vagina, ganglios linfáticos en la zona y hasta la pared pélvica; puede incluso llegar parcialmente hasta el riñón y afectar su funcionamiento. Si su condición se mantiene estable y constante, sin mejorar, empeorar o sumarle otras condiciones, se estima que puede tener alrededor de {meses} meses de vida útil; es un resultado teórico, no reemplaza un diagnóstico médico real. Se le indica continuar con los tratamientos requeridos con rigurosidad y seguir las indicaciones dadas por los especialistas para evitar la progresión del cáncer hasta una etapa terminal y más crítica."
          st.warning(mensaje)
          imagen_ilustrativa = "imagenes/estadio_3.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
          nombre_imagen = graficar_logistica(P0, K, r)
          st.image(nombre_imagen, caption="📊 Evolución estimada del tamaño tumoral", use_container_width=True)
        elif st.session_state.inicio == "No" and diagfinal >= 6:
          mensaje = f"Muestra indicios de poder estar en Estadio IV, puede ser una etapa temprana o media, durante esta fase el cáncer se ha extendido hacia otros tejidos y órganos aparte del útero y la vagina, puede generar afectaciones en ciertas actividades y necesidades cotidianas; generar sensación de cansancio y dolores constantes en diversas áreas del cuerpo, esta etapa puede ser descrita como 'Metástasis' también. Se le recomienda hacer una visita al especialista lo más pronto posible y empezar a tratar su situación con rigurosidad en el tiempo más próximo, posiblemente realizar una biopsia para identificar el grado de Estadio IV en que se encuentre para que los especialistas puedan determinar cómo proseguir en su tratamiento."
          st.error(mensaje)
          imagen_ilustrativa = "imagenes/estadio_4.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
          nombre_imagen = None
        elif st.session_state.inicio == "No" and diagfinal >= 4:
          mensaje = f"Muestra indicios de poder estar en un Estadio III avanzado o entrando a Estadio IV, durante esta etapa el cáncer está extendiéndose hacia otros tejidos y órganos aparte del útero y la vagina, puede generar afectaciones en ciertas actividades y necesidades cotidianas. Se le recomienda hacer una visita al especialista lo más pronto posible y empezar a tratar su situación con rigurosidad en el tiempo más próximo, posiblemente realizar una biopsia para identificar el grado de Estadio IV en que se encuentre para que los especialistas puedan determinar cómo proseguir en su tratamiento."
          st.error(mensaje)
          imagen_ilustrativa = "imagenes/estadio_34.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor (E: Estadio III; F: Estadio IV)", use_container_width=True)
          nombre_imagen = None
        elif st.session_state.inicio == "No" and diagfinal >= 2:
          mensaje = f"Muestra síntomas que indican estar en Estadio III medio/avanzado, en esta etapa el tumor ha invadido el útero, gran parte de la vagina, ganglios linfáticos en la zona y hasta la pared pélvica; puede incluso llegar parcialmente hasta el riñón, afectar su funcionamiento y causar molestias al orinar o defecar al afectar la vejiga o el recto hasta cierto punto. Se le recomienda hacer una visita al especialista lo más pronto posible y empezar a tratar su situación con rigurosidad en el tiempo más próximo para intentar preservar su salud en la medida de lo posible y evitar la progresión del cáncer hasta una etapa totalmente terminal."
          st.warning(mensaje)
          imagen_ilustrativa = "imagenes/estadio_33.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
          nombre_imagen = None
        elif st.session_state.inicio == "No" and diagfinal >= 0:
          mensaje = f"Muestra síntomas por los que se podría considerar estar en etapa temprana/media del Estadio III, en esta etapa el tumor ha invadido el útero, gran parte de la vagina, ganglios linfáticos en la zona y hasta la pared pélvica; puede incluso llegar parcialmente hasta el riñón y afectar su funcionamiento. Se le recomienda hacer una visita al especialista lo más pronto posible y empezar a tratar su situación con rigurosidad en el tiempo más próximo para intentar preservar su salud en la medida de lo posible y evitar la progresión del cáncer hasta una etapa totalmente terminal."
          st.warning(mensaje)
          imagen_ilustrativa = "imagenes/estadio_3.png"
          st.image(imagen_ilustrativa, caption="Posible estado cercano del tumor", use_container_width=True)
          nombre_imagen = None

        st.session_state.resultado = mensaje
        st.session_state.resultado_generado = True
        st.session_state.resultado_guardado = False  # Por si el usuario quiere repetir

        # Mostrar botón para guardar
        # 🟠 Advertencia si intenta salir sin guardar
        if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
            st.warning("Guarda tu resultado y podrás verlo en una siguiente sesión.")

        if st.session_state.resultado_generado and not st.session_state.resultado_guardado:
           if st.button("Guardar resultado"):
                 datos_resultado = {
                      "nombre": nombre,
                      "resultado": mensaje,
                      "fecha_resultado": datetime.now().strftime("%Y-%m-%d"),
                 }

                 # Solo agregar si existen
                 if nombre_imagen:
                      datos_resultado["grafica"] = nombre_imagen

                 if imagen_ilustrativa:
                      datos_resultado["imagen_ilustrativa"] = imagen_ilustrativa

                 usuarios[id_usuario] = datos_resultado
                 guardar_usuarios(usuarios)
                 st.session_state.resultado_guardado = True
                 st.success("✅ Resultado guardado.")

'''

with open("app.py", "w") as f:
    f.write(app_code)

# 4. Ejecutar la app con ngrok
import threading, time

time.sleep(5)

public_url = ngrok.connect(8501)
print("✅ Tu app está disponible en:", public_url)
